# Generated by Django 3.2.5 on 2022-10-13 20:26

from django.db import migrations
import route_app.data.django_aux.model_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', route_app.data.django_aux.model_fields.HexIdField(default=route_app.data.django_aux.model_fields.generate_uuid, max_length=128, primary_key=True, serialize=False)),
            ],
        ),
    ]
