# Generated by Django 3.2.5 on 2022-10-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='route',
            name='user_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
